config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', as: :new_user_session
    get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  post 'locale/set', to: 'locale#update'

  resources :cards, only: [:index, :show] do
    collection do
      get 'mine', to: redirect('cards')
      get 'select'
    end
  end

  get 'cards/no/:id', to: 'cards#no'
  get 'cards/ex/:id', to: 'cards#ex'

  get 'packs', to: 'card_packs#index'

  resources :npcs, only: [:index, :show] do
    post 'add'
    post 'remove'
    post 'defeated/update', on: :collection, to: 'npcs#update_defeated', as: :update_defeated
  end

  resources :cards, only: [] do
    post 'add'
    post 'remove'
    post 'set', on: :collection
  end

  resources :decks do
    get 'mine', as: :my, on: :collection
    post 'upvote'
    post 'downvote'
  end

  get 'users/:uid', to: 'users#show', as: :user
  get 'user/settings', to: 'users#edit'
  post 'user/settings', to: 'users#update'
  get 'user/import', to: 'users#import'
  post 'user/import', to: 'users#submit'

  namespace :api do
    %w(npcs cards packs decks).each do |model|
      resources model, only: [:index, :show], defaults: { format: :json }
    end

    resources :users, only: :show
  end

  get 'api/docs', to: redirect('https://documenter.getpostman.com/view/1779678/TzXzDHRR')

  get 'commands', to: 'static#commands'
  post 'discord/interactions'

  namespace :admin do
    resources :users, only: :index
    resources :npcs, only: [:index, :edit, :update]
    resources :cards, only: [:index, :edit, :update] do
      delete 'delete_sources'
    end
  end

  get '404', to: 'static#not_found', as: :not_found
  match "api/*path", via: :all, to: -> (_) { [404, { 'Content-Type' => 'application/json' },
                                              ['{"status": 404, "error": "Not found"}'] ] }
  match "*path", via: :all, to: redirect('404')

  # Quick 404 for missing images
  scope format: true, constraints: { format: 'png' } do
    get "/*missing", to: proc { [404, {}, ['']] }
  end

  root 'static#home'
end

app/models/card.rb
# == Schema Information
#
# Table name: cards
#
#  id               :bigint(8)        not null, primary key
#  patch            :string(255)
#  card_type_id     :integer          not null
#  stars            :integer          not null
#  top              :integer          not null
#  right            :integer          not null
#  bottom           :integer          not null
#  left             :integer          not null
#  buy_price        :integer
#  sell_price       :integer          not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  order            :integer
#  name_en          :string(255)      not null
#  name_de          :string(255)      not null
#  name_fr          :string(255)      not null
#  name_ja          :string(255)      not null
#  description_en   :text(65535)      not null
#  description_de   :text(65535)      not null
#  description_fr   :text(65535)      not null
#  description_ja   :text(65535)      not null
#  order_group      :integer
#  deck_order       :integer
#  formatted_number :string(255)      not null
#

class Card < ApplicationRecord
  belongs_to :type, class_name: 'CardType', foreign_key: :card_type_id
  has_many :npc_cards
  has_many :npcs, through: :npc_cards
  has_many :npc_rewards
  has_many :npc_sources, through: :npc_rewards, source: :npc
  has_many :sources
  has_many :deck_cards
  has_many :decks, through: :deck_cards
  has_many :pack_cards
  has_many :packs, through: :pack_cards
  has_and_belongs_to_many :users
  has_one :achievement, required: false

  after_save :touch_related

  accepts_nested_attributes_for :sources

  translates :name, :description

  scope :standard, -> { where(order_group: 0) }
  scope :ex,       -> { where.not(order_group: 0) }

  def ex?
    order_group != 0
  end

  def formatted_number
    ex? ? "Ex. #{order}" : "No. #{order}"
  end

  def ownership
    Redis.current.hget(:ownership, id.to_s) || '0%'
  end

  def stat(side)
    value = self[side]
    value == 10 ? 'A' : value
  end

  def stats
    "#{top} #{right} #{bottom} #{left}".gsub(/10/, 'A')
  end

  def total_stats
    top + right + bottom + left
  end

  def self.no(number)
    Card.find_by(formatted_number: "No. #{number}")
  end

  def self.ex(number)
    Card.find_by(formatted_number: "Ex. #{number}")
  end

  private
  def touch_related
    npcs.touch_all
    npc_sources.touch_all
    decks.touch_all
    packs.touch_all
  end
end

app/models/card_type.rb
# == Schema Information
#
# Table name: card_types
#
#  id         :bigint(8)        not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  name_en    :string(255)      not null
#  name_de    :string(255)      not null
#  name_fr    :string(255)      not null
#  name_ja    :string(255)      not null
#

class CardType < ApplicationRecord
  has_many :cards

  translates :name
end

app/controllers/admin/cards_controller.rb
class Admin::CardsController < AdminController
  before_action :set_card, only: [:edit, :update]

  def index
    @q = Card.all.ransack(params[:q])
    @cards = @q.result.includes(:npc_sources, :sources, :packs, :achievement)
      .order(patch: :desc, order_group: :desc, order: :desc)
      .paginate(page: params[:page])
  end

  def edit
    build_sources
  end

  def update
    update_params = card_params
    update_params[:sources_attributes].reject! { |_, source| source[:origin].blank? || source[:name].blank? }

    if @card.update(update_params)
      flash[:success] = 'Card has been updated.'
      redirect_to edit_admin_card_path(@card)
    else
      flash[:error] = 'There was a problem updating the card.'
      build_sources
      render :edit
    end
  end

  def delete_sources
    @card = Card.find(params[:card_id])
    @card.sources.delete_all

    flash[:success] = 'Card sources have been deleted.'
    redirect_to edit_admin_card_path(@card)
  end

  private
  def set_card
    @card = Card.find(params[:id])
  end

  def build_sources
    2.times { @card.sources.build }
  end

  def card_params
    params.require(:card).permit(:name, :buy_price, :patch, sources_attributes: [:id, :card_id, :origin, :name])
  end
end

app/controllers/api/cards_controller.rb
class Api::CardsController < ApiController
  def index
    @query_params = sanitize_query_params
    query = Card.all.ransack(@query_params)
    @cards = query.result.includes(:type, :sources, :packs, :achievement, npc_sources: [:location, :quest, :rules])
      .order(:patch, :order_group, :order).limit(params[:limit])
  end

  def show
    @card = Card.find_by(id: params[:id])
    render_not_found unless @card.present?
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_cards, only: [:index, :mine]

  def index
    if user_signed_in?
      @user_cards = current_user.cards.pluck(:id)
      @count = (@user_cards & @cards.pluck(:id)).count
      @total = @cards.present? ? @cards.count : Card.count
    else
      render_sign_in_flash
    end
  end

  def select
    if user_signed_in?
      @cards = Card.all.order(:order_group, :order)
      @user_cards = current_user.cards.pluck(:id)
    else
      flash[:alert] = 'You must sign in to manage your cards.'
      redirect_to cards_path
    end
  end

  def show
    if params[:id].match?(/\A\d+\z/)
      @card = Card.find(params[:id])
    else
      @card = Card.find_by(name_en: params[:id])
    end

    redirect_to not_found_path unless @card.present?
  end

  def add
    if user = current_user
      user.add_card(params[:card_id])
      head :no_content
    else
      head :not_found
    end
  end

  def remove
    if user = current_user
      user.remove_card(params[:card_id])
      head :no_content
    else
      head :not_found
    end
  end

  def set
    current_user.set_cards(set_params[:cards].split(','))
    redirect_to cards_path
  end

  def no
    if card = Card.no(params[:id])
      redirect_to card_path(card)
    else
      flash[:error] = 'That page could not be found.'
      redirect_to cards_path
    end
  end

  def ex
    if card = Card.ex(params[:id])
      redirect_to card_path(card)
    else
      flash[:error] = 'That page could not be found.'
      redirect_to cards_path
    end
  end

  private
  def set_cards
    @type = params[:source_type]
    query = params[:q] || {}

    case @type
    when 'NPC'
      cards = Card.joins(:npc_sources)
    when 'Pack'
      cards = Card.joins(:packs)
    when 'MGP'
      cards = Card.where.not(buy_price: nil)
    when 'Achievement'
      cards = Card.joins(:achievement)
    else
      query[:sources_origin_eq] = @type if @type.present?
      cards = Card.all
    end

    @q = cards.ransack(query)
    @cards = @q.result.includes(:npc_sources, :sources, :packs, :achievement, :type)
      .order(patch: :desc, order_group: :desc, order: :desc).uniq
    @ownership = Redis.current.hgetall(:ownership)
  end

  def set_params
    params.permit(:cards)
  end
end

app/helpers/admin/cards_helper.rb
module Admin::CardsHelper
  def origin_options
    Source.origins - %w(NPC Pack MGP Achievement)
  end
end

app/helpers/cards_helper.rb
module CardsHelper
  def small_image(card)
    image_tag('blank.png', class: 'small', style: "background-position: -#{40 * (card.id - 1)}px 0")
  end

  def large_image(card)
    image_tag('blank.png', class: 'large', style: "background-position: -#{104 * (card.id - 1)}px 0")
  end

  def type_image(card)
    if card.card_type_id > 0
      image_tag('blank.png', class: 'type', style: "background-position: -#{20 * (card.card_type_id - 1)}px 0",
                data: { toggle: 'tooltip', placement: 'top', title: card.type.name })
    end
  end

  def card_number_badge(card)
    content_tag(:span, card.formatted_number, class: 'badge badge-secondary')
  end

  def stars(card)
    (fa_icon('star') * card.stars).html_safe
  end

  def rarity_options
    (1..5).to_a.reverse.map { |x| ["\u2605" * x, x] }
  end

  def select_tooltip_delay
    '{"show": 500, "hide": 0 }'
  end

  def format_description(card)
    card.description.gsub("\n", '<br>')
      .gsub(/\*(.*?)\*/, '<i>\1</i>')
      .html_safe
  end

  def format_price(price)
    if price > 0
      "#{number_with_delimiter(price)} MGP"
    else
      'N/A'
    end
  end

  def user_ownership(card)
    if user_signed_in?
      owned = current_user.cards.include?(card)

      content_tag(:span, data: { toggle: 'tooltip' }, title: owned ? 'You own this card.' : 'You do not own this card.') do
        fa_icon(owned ? 'check' : 'times')
      end
    end
  end

  def sources(card)
    sources = card.npc_sources.map { |npc| link_to(npc.name, npc_path(npc)) }

    sources += card.sources.pluck(:name).map do |name|
      I18n.t(name.delete('.*'), default: name)
    end

    card.packs.each do |pack|
      sources << link_to(pack.name, packs_path(nil, anchor: pack.id))
    end

    if card.achievement.present?
      sources << link_to(card.achievement.name, "https://ffxivcollect.com/achievements/#{card.achievement.id}",
                         target: '_blank', data: { toggle: 'tooltip' }, title: card.achievement.description)
    end

    sources << format_price(card.buy_price) if card.buy_price
    sources
  end
end

app/views/cards/_form.html.erb
<%= search_form_for(@q, url: url, enforce_utf8: false, class: 'form form-inline card-search search-form d-flex justify-content-center') do |f| %>
  <%= f.search_field "name_#{I18n.locale}_cont", placeholder: 'Name', size: 25, class: 'form-control form-control-sm' %>
  <%= f.search_field 'order_eq', placeholder: 'Number', size: 10, class: 'form-control form-control-sm' %>
  <%= f.collection_select :card_type_id_eq, CardType.all, :id, :name,
    { include_blank: 'All Types' }, class: 'form-control form-control-sm' %>
  <%= f.select :stars_eq, rarity_options, { include_blank: 'All Rarities' }, class: 'form-control form-control-sm' %>
  <%= select_tag :source_type, options_for_select(Source.origins, @type),
    include_blank: 'All Sources', class: 'form-control form-control-sm' %>
  <%= f.submit 'Search', name: nil, class: 'btn btn-secondary btn-sm mr-0' %>
<% end %>

app/views/cards/_large.html.erb
<%= link_to card_path(card) do %>
  <div data-toggle="tooltip" data-placement="bottom" title="<%= card.name %>" class="card-large">
    <%= large_image(card) %>
  </div>
<% end %>

app/views/cards/_owned.html.erb
Owned
<span data-toggle="tooltip" title="Percentage of active, public users who own this card.">
  <%= fa_icon('question-circle') %>
</span>

app/views/cards/_stats.html.erb
<div class="d-flex flex-column stats">
  <div class="d-flex justify-content-center">
    <span><%= card.stat(:top) %></span>
  </div>
  <div class="d-flex justify-content-around">
    <span><%= card.stat(:left) %></span>
    <span><%= card.stat(:right) %></span>
  </div>
  <div class="d-flex justify-content-center">
    <span><%= card.stat(:bottom) %></span>
  </div>
</div>

app/views/cards/_table_data.html.erb
<% cards.each do |card| %>
  <tr class="card-row<%= ' has-card' if local_assigns[:user_cards]&.include?(card.id) %>">
    <td class="hide-xs px-2">
      <%= card_number_badge(card) %>
    </td>
    <td <%= 'class="owned"'.html_safe if local_assigns[:owned_cards]&.include?(card.id) %>>
      <%= link_to(card_path(card)) do %>
        <%= small_image(card) %>
      <% end %>
    </td>
    <td class="hide-xs">
      <%= link_to(card.name, card_path(card), class: 'name') %>
    </td>
    <td data-value="<%= card.card_type_id %>"><%= type_image(card) %></td>
    <td class="no-wrap" data-value="<%= card.stars %>"><%= stars(card) %></td>
    <td data-value="<%= card.total_stats %>">
      <div class="d-flex flex-column align-items-center stats">
        <div class="d-flex justify-content-center">
          <span><%= card.stat(:top) %></span>
        </div>
        <div class="d-flex justify-content-around">
          <span><%= card.stat(:left) %></span>
          <span><%= card.stat(:right) %></span>
        </div>
        <div class="d-flex justify-content-center">
          <span><%= card.stat(:bottom) %></span>
        </div>
      </div>
    </td>
    <% unless local_assigns[:skip_source] %>
      <td class="hide-xs">
        <ul class="list-unstyled mb-0">
          <% sources(card).each do |source| %>
            <li><%= source %></li>
          <% end %>
        </ul>
      </td>
    <% end %>
    <% if local_assigns[:ownership] %>
      <td class="hide-xs text-center" data-value="<%= ownership.fetch(card.id.to_s, '0%').delete('%') %>">
        <%= ownership.fetch(card.id.to_s, '0%') %>
      </td>
    <% end %>
    <% unless local_assigns[:skip_source] %>
      <td class="text-center" data-value="<%= card.patch %><%= card.id %>"><%= card.patch %></td>
    <% end %>
    <% if local_assigns[:user_cards] %>
      <td class="text-center">
        <% if user_cards.include?(card.id) %>
          <input type="checkbox" class="card-toggle" data-path="<%= card_remove_path(card) %>" checked>
        <% else %>
          <input type="checkbox" class="card-toggle" data-path="<%= card_add_path(card) %>">
        <% end %>
      </td>
    <% end %>
    <% if local_assigns[:deck] %>
      <td class="text-center">
        <%= button_tag(class: 'btn btn-secondary btn-sm deck-toggle',
                       disabled: deck.size >= 5 && !deck.include?(card.id),
                       data: { card_id: card.id, action: deck.include?(card.id) ? 'remove' : 'add' }) do %>
          <% if deck.include?(card.id) %>
            <%= fa_icon('minus', text: 'Remove') %>
          <% else %>
            <%= fa_icon('plus', text: 'Add') %>
          <% end %>
        <% end %>
      </td>
    <% end %>
  </tr>
<% end %>

app/views/cards/index.html.erb
<% title('Cards') %>
<%= javascript_tag "window._token = '#{form_authenticity_token}'" %>

<% if user_signed_in? %>
  <div class="d-block d-md-none">
    <%= render 'form', url: cards_path %>
  </div>
  <div class="d-flex justify-content-between align-items-end mb-1">
    <div class="no-wrap mb-1">
      <%= link_to 'Select Your Cards', select_cards_path,
        class: "btn btn-secondary btn-sm#{' btn-attention' if @user_cards.empty?}" %>
    </div>
    <div class="d-none d-md-block">
      <%= render 'form', url: cards_path %>
    </div>
    <div class="d-flex align-items-center no-wrap mb-1">
      <label for="toggle-owned" class="mb-0 mr-1">Hide Owned</label>
      <input type="checkbox" id="toggle-owned" />
    </div>
  </div>
  <%= render 'layouts/progress', value: @count, min: 0, max: @total %>
<% else %>
  <%= render 'form', url: cards_path %>
<% end %>
<table class="table table-striped table-sm shadow p-3 mt-2 mb-5 sortable my-cards">
  <thead>
    <tr>
      <th scope="col" class="hide-xs">#</th>
      <th scope="col" data-defaultsort="disabled"></th> <!-- Image -->
      <th scope="col" class="hide-xs">Name</th>
      <th scope="col" class="pr-3">Type</th>
      <th scope="col">Rarity</th>
      <th scope="col" class="text-center">Stats</th>
      <th scope="col" class="hide-xs">Source</th>
      <th scope="col" class="text-center hide-xs">Owned</th>
      <th scope="col" class="text-center">Patch</th>
      <% if user_signed_in? %>
        <th scope="col" class="text-center" data-defaultsort="disabled"></th> <!-- Checkbox -->
      <% end %>
    </tr>
  </thead>
  <tbody>
    <%= render 'table_data', cards: @cards, user_cards: @user_cards, ownership: @ownership %>
  </tbody>
</table>

app/views/cards/select.html.erb
<% title('Select Cards') %>

<div class="card-buttons d-flex justify-content-between align-items-center mx-auto mb-1">
  <button type="button" class="btn btn-secondary btn-sm" id="nav-prev"><%= fa_icon('arrow-left') %> Prev</button>
  <span id="page">Page 1</span>
  <button type="button" class="btn btn-secondary btn-sm" id="nav-next">Next <%= fa_icon('arrow-right') %></button>
</div>
<div class="card card-page mx-auto pl-2 pt-2">
  <div class="d-flex flex-wrap align-items-start">
    <% @cards.each do |card| %>
      <div class="card-select<%= ' missing' unless @user_cards.include?(card.id) %><%= ' ex' if card.ex? %>"
           data-id="<%= card.id %>" data-toggle="tooltip" data-placement="top" data-delay="<%= select_tooltip_delay %>"
           title="<%= card.name %>">
        <%= small_image(card) %>
      </div>
    <% end %>
  </div>
</div>
<div class="card-buttons d-flex flex-column mx-auto mt-1 px-1">
  <span class="font-weight-bold ml-auto mb-1" id="total">Total: <%= @user_cards.size %> / <%= Card.count %></span>
  <div class="d-flex">
    <button type="button" class="btn btn-success btn-sm w-50 mr-1" id="add-all">Add All</button>
    <button type="button" class="btn btn-danger btn-sm w-50 ml-1" id="remove-all">Remove All</button>
  </div>
</div>
<div class="card mt-4 mb-2">
  <div class="card-header">
    <h5>How To Use</h5>
  </div>
  <div class="card-body">
    <ol class="my-2">
      <li>If you own more than half the cards, click the <b>Add All</b> button.</li>
      <li>For each page, add/remove cards until it matches your in-game <b>Card List</b>.</li>
      <li>Confirm that your <b>Total</b> matches your in-game Card List.</li>
      <li>Click <b>Save Cards</b>.</li>
    </ol>
  </div>
</div>
<%= form_tag(set_cards_path, class: 'text-right') do %>
  <%= hidden_field_tag('cards', @user_cards.join(','), id: 'card-ids') %>
  <%= link_to 'Reset', select_cards_path, class: 'btn btn-danger' %>
  <%= submit_tag('Save Cards', class: 'btn btn-primary', id: 'submit') %>
<% end %>

app/views/cards/show.html.erb
<% title(@card.name) %>
<% description(@card.description.truncate(150)) %>
<% image(image_url("cards/large/#{@card.id}.png", skip_pipeline: true)) %>

<div class="col-12 col-lg-8 offset-0 offset-lg-2">
  <div class="card">
    <div class="card-header d-flex align-items-center justify-content-between">
      <h5 class="card-title"><%= @card.name %></h5>
      <%= card_number_badge(@card) %>
    </div>
    <div class="card-body">
      <div class="d-flex">
        <%= render 'large', card: @card %>
        <div class="d-flex flex-column ml-4">
          <div class="d-flex flex-wrap card-info">
            <% if @card.card_type_id > 0 %>
              <div class="text-center">
                <dt>Type</dt>
                <dd><%= type_image(@card) %></dd>
              </div>
            <% end %>
            <div>
              <dt>Rarity</dt>
              <dd><%= stars(@card) %></dd>
            </div>
            <div>
              <dt>Stats</dt>
              <dd><%= render 'stats', card: @card %></dd>
            </div>
            <div>
              <dt>
                <%= render 'owned' %>
              </dt>
              <dd>
                <%= user_ownership(@card) %>
                <%= @card.ownership %>
              </dd>
            </div>
            <div>
              <dt>Sale Price</dt>
              <dd><%= format_price(@card.sell_price) %></dd>
            </div>
            <div>
              <dt>Patch</dt>
              <dd><%= @card.patch %></dd>
            </div>
          </div>
          <div>
            <dt>Source</dt>
            <dd>
              <ul class="list-unstyled">
                <% sources(@card).each do |source| %>
                  <li><%= source %></li>
                <% end %>
              </ul>
            </dd>
          </div>
        </div>
      </div>
      <hr />
      <dt>Description</dt>
      <dd><%= format_description(@card) %></dd>
    </div>
  </div>
</div>