config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', as: :new_user_session
    get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  post 'locale/set', to: 'locale#update'

  resources :cards, only: [:index, :show] do
    collection do
      get 'mine', to: redirect('cards')
      get 'select'
    end
  end

  get 'cards/no/:id', to: 'cards#no'
  get 'cards/ex/:id', to: 'cards#ex'

  get 'packs', to: 'card_packs#index'

  resources :npcs, only: [:index, :show] do
    post 'add'
    post 'remove'
    post 'defeated/update', on: :collection, to: 'npcs#update_defeated', as: :update_defeated
  end

  resources :cards, only: [] do
    post 'add'
    post 'remove'
    post 'set', on: :collection
  end

  resources :decks do
    get 'mine', as: :my, on: :collection
    post 'upvote'
    post 'downvote'
  end

  get 'users/:uid', to: 'users#show', as: :user
  get 'user/settings', to: 'users#edit'
  post 'user/settings', to: 'users#update'
  get 'user/import', to: 'users#import'
  post 'user/import', to: 'users#submit'

  namespace :api do
    %w(npcs cards packs decks).each do |model|
      resources model, only: [:index, :show], defaults: { format: :json }
    end

    resources :users, only: :show
  end

  get 'api/docs', to: redirect('https://documenter.getpostman.com/view/1779678/TzXzDHRR')

  get 'commands', to: 'static#commands'
  post 'discord/interactions'

  namespace :admin do
    resources :users, only: :index
    resources :npcs, only: [:index, :edit, :update]
    resources :cards, only: [:index, :edit, :update] do
      delete 'delete_sources'
    end
  end

  get '404', to: 'static#not_found', as: :not_found
  match "api/*path", via: :all, to: -> (_) { [404, { 'Content-Type' => 'application/json' },
                                              ['{"status": 404, "error": "Not found"}'] ] }
  match "*path", via: :all, to: redirect('404')

  # Quick 404 for missing images
  scope format: true, constraints: { format: 'png' } do
    get "/*missing", to: proc { [404, {}, ['']] }
  end

  root 'static#home'
end

app/models/npc.rb
# == Schema Information
#
# Table name: npcs
#
#  id          :bigint(8)        not null, primary key
#  x           :decimal(3, 1)
#  y           :decimal(3, 1)
#  resident_id :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  quest_id    :integer
#  patch       :string(255)
#  name_en     :string(255)      not null
#  name_de     :string(255)      not null
#  name_fr     :string(255)      not null
#  name_ja     :string(255)      not null
#  location_id :integer          not null
#  difficulty  :decimal(3, 2)
#  excluded    :boolean          default(FALSE)
#

class NPC < ApplicationRecord
  has_many :npc_cards
  has_many :npc_rewards
  has_many :cards, through: :npc_cards
  has_many :fixed_cards, -> { where('npc_cards.fixed = true') }, through: :npc_cards, source: :card
  has_many :variable_cards, -> { where('npc_cards.fixed = false') }, through: :npc_cards, source: :card
  has_many :rewards, through: :npc_rewards, source: :card
  has_many :decks
  has_and_belongs_to_many :users
  has_and_belongs_to_many :rules
  belongs_to :location
  belongs_to :quest, optional: true

  after_save :touch_related

  scope :valid, -> { where(excluded: false) }

  translates :name

  private
  def touch_related
    decks.touch_all
    rewards.touch_all
  end
end

app/controllers/admin/npcs_controller.rb
class Admin::NPCsController < AdminController
  before_action :set_npc, only: [:edit, :update]

  def index
    @q = NPC.all.ransack(params[:q])
    @npcs = @q.result.includes(:rules, :location, :quest).order(patch: :desc, id: :desc).paginate(page: params[:page])
  end

  def edit
  end

  def update
    paramz = npc_params
    quest = paramz.delete(:quest)

    if quest.present?
      quest_id = Quest.find_by(name_en: quest)&.id

      if quest_id.present?
        paramz[:quest_id] = quest_id
      else
        flash[:error] = "Could not find quest \"#{quest}\"."
        return render :edit
      end
    end

    if @npc.update(paramz)
      flash[:success] = 'NPC has been updated.'
      redirect_to edit_admin_npc_path(@npc)
    else
      flash[:error] = 'There was a problem updating the NPC.'
      render :edit
    end
  end

  private
  def set_npc
    @npc = NPC.find(params[:id])
  end

  def npc_params
    params.require(:npc).permit(:name, :quest, :x, :y, :patch, :excluded)
  end
end

app/controllers/api/npcs_controller.rb
class Api::NPCsController < ApiController
  before_action :set_options

  def index
    @query_params = sanitize_query_params.except(:deck)
    result = NPC.all.ransack(@query_params).result
    result = result.includes(fixed_cards: :type, variable_cards: :type) if @include_deck
    @npcs = result.includes(:location, :quest, :rules, rewards: :type).order(:patch, :id).limit(params[:limit])
  end

  def show
    @npc = NPC.includes(fixed_cards: :type, variable_cards: :type, rewards: :type).find_by(id: params[:id])
    render_not_found unless @npc.present?
  end

  private
  def set_options
    @include_deck = params[:deck].present?
  end
end

app/controllers/npcs_controller.rb
class NPCsController < ApplicationController
  def index
    @location = params[:location]
    @rule = params[:rule]
    query = {}

    if @location.present?
      query["location_region_#{I18n.locale}_eq"] = @location
    end

    if @rule.present?
      query["rules_name_#{I18n.locale}_matches_any"] = @rule
    end

    @q = NPC.all.ransack(query)
    @npcs = @q.result.includes(:rewards, :rules, :location, :quest).order(patch: :desc, id: :desc)
    @valid_npcs = @npcs.valid

    if user_signed_in?
      @user_cards = current_user.cards.pluck(:id)
      @incomplete = @npcs.joins(:rewards).where('cards.id not in (?)', @user_cards).pluck(:id).uniq
      @defeated = current_user.npcs.pluck(:id)
      @total = @valid_npcs.present? ? @valid_npcs.count : NPC.count
      @count = (@defeated & @valid_npcs.pluck(:id)).count
    else
      render_sign_in_flash
      @user_cards = []
      @incomplete = []
      @defeated = []
    end
  end

  def show
    if params[:id].match?(/\A\d+\z/)
      @npc = NPC.find(params[:id])
    else
      @npc = NPC.find_by(name_en: params[:id])
    end

    return redirect_to not_found_path unless @npc.present?

    @rewards = @npc.rewards
  end

  def add
    if user = current_user
      user.add_npc(params[:npc_id])
      head :no_content
    else
      head :not_found
    end
  end

  def remove
    if user = current_user
      user.remove_npc(params[:npc_id])
      head :no_content
    else
      head :not_found
    end
  end

  def update_defeated
    current_user.add_defeated_npcs
    redirect_to npcs_path
  end

  private
  def set_params
    params.permit(:npcs)
  end
end

app/helpers/admin/npcs_helper.rb
module Admin::NPCsHelper
end

app/helpers/npcs_helper.rb
module NPCsHelper
  def location(npc, inline: false)
    "#{npc.location.name}#{inline ? ' ' : '<br>'}(#{npc.x}, #{npc.y})".html_safe
  end

  def quest(npc)
    if npc.quest.present?
      link_to(npc.quest.name, "https://www.garlandtools.org/db/#quest/#{npc.quest_id}", target: '_blank')
    end
  end

  def format_npc_name(npc)
    if npc.excluded?
      tooltip = content_tag(:span, fa_icon('exclamation-circle'), data: { toggle: 'tooltip' },
                            title: 'Does not count for Triple Team achievements')
      "#{npc.name} #{tooltip}".html_safe
    else
      npc.name
    end
  end

  def format_rules(npc, inline: false)
    npc.rules.map(&:name).sort.join(inline ? ', ' : '<br>').html_safe
  end

  def difficulty(npc)
    (fa_icon('star') * npc.difficulty.ceil).html_safe
  end

  def npc_defeated?(npc)
    current_user.npcs.include?(npc)
  end

  def npc_rule_options(selected)
    options_for_select(Rule.joins(:npcs).order("name_#{I18n.locale}").uniq.map(&:name), selected)
  end
end

app/views/npcs/index.html.erb
<% title('NPCs') %>

<%= javascript_tag "window._token = '#{form_authenticity_token}'" %>
<div class="row">
  <div class="col-12 col-md-6 mb-2 mb-md-0 d-flex flex-wrap justify-content-center justify-content-md-start">
    <%= form_tag(npcs_path, method: :get, enforce_utf8: false,
                 class: 'form form-inline search-form d-flex flex-wrap', id: 'npc-search') do %>
      <%= select_tag :location, options_for_select(Location.order(:id).map(&:region).uniq, @location),
        include_blank: 'All Locations', class: 'form-control form-control-sm mt-0' %>
      <%= select_tag :rule, npc_rule_options(@rule), include_blank: 'All Rules', class: 'form-control form-control-sm' %>
      <% if user_signed_in? %>
        <%= link_to 'Update Defeated', update_defeated_npcs_path, method: :post,
          class: 'btn btn-sm btn-secondary mt-2 mt-sm-0',
          data: { confirm: 'All NPCs with exclusive cards you have obtained will be marked as defeated.' } %>
      <% end %>
    <% end %>
  </div>
  <div class="col-12 col-md-6 d-flex justify-content-center justify-content-md-end align-items-center">
    <% if user_signed_in? %>
      <div class="">
        <div class="form-check form-check-inline">
          <input class="form-check-input" type="radio" name="display" id="show-all" checked />
          <label class="form-check-label" for="show-all">Show All</label>
        </div>
        <div class="form-check form-check-inline">
          <input class="form-check-input" type="radio" name="display" id="hide-completed" />
          <label class="form-check-label" for="hide-completed">Missing Rewards</label>
        </div>
        <div class="form-check form-check-inline">
          <input class="form-check-input" type="radio" name="display" id="hide-defeated" />
          <label class="form-check-label" for="hide-defeated">Undefeated</label>
        </div>
        <div class="form-check form-check-inline mr-0">
          <input class="form-check-input" type="radio" name="display" id="hide-finished" />
          <label class="form-check-label" for="hide-finished">Unfinished</label>
        </div>
      </div>
    <% end %>
  </div>
</div>
<% if user_signed_in? %>
  <div class="mt-2">
    <%= render 'layouts/progress', value: @count, min: 0, max: @valid_npcs.size %>
  </div>
<% end %>
<table class="table table-striped table-sm shadow p-3 mt-2 mb-5 sortable" id="npcs">
  <thead>
    <tr>
      <th scope="col" class="npc-name">Name</th>
      <th scope="col">Location</th>
      <th scope="col" class="hide-xs">Rules</th>
      <th scope="col" class="hide-xs">Difficulty</th>
      <th scope="col" class="hide-sm quest-name">Quest</th>
      <th scope="col">Rewards</th>
      <th scope="col" class="hide-xs text-center">Patch</th>
      <% if user_signed_in? %>
        <th scope="col" class="text-center" data-defaultsort="disabled"></th> <!-- Won -->
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @npcs.each do |npc| %>
      <tr class="npc-row<%= ' completed' if !@incomplete.include?(npc.id) %><%= ' defeated' if @defeated.include?(npc.id) %><%= ' excluded' if npc.excluded? %>">
        <td class="npc-name"><%= link_to(format_npc_name(npc), npc_path(npc), class: 'name') %></td>
        <td><%= location(npc) %></td>
        <td class="hide-xs"><%= format_rules(npc) %></td>
        <td class="hide-xs" data-value="<%= npc.difficulty %>"><%= difficulty(npc) %></td>
        <td class="hide-sm quest-name"><%= quest(npc) %></td>
        <td class="npc-rewards" data-value="<%= npc.rewards.size %>">
          <div class="d-flex flex-wrap card-list">
            <% npc.rewards.each do |card| %>
              <% if user_signed_in? %>
                <div class="card-toggle<%= ' owned' if @user_cards.include?(card.id) %>"
                  data-path="<%= @user_cards.include?(card.id) ? card_remove_path(card) : card_add_path(card) %>"
                  data-toggle="tooltip" data-placement="top" title="<%= card.name %>">
                  <%= small_image(card) %>
                </div>
              <% else %>
                <%= link_to card_path(card) do %>
                  <div data-toggle="tooltip" data-placement="top" title="<%= card.name %>">
                    <%= small_image(card) %>
                  </div>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </td>
        <td class="hide-xs text-center" data-value="<%= npc.patch %><%= npc.id %>"><%= npc.patch %></td>
        <% if user_signed_in? %>
          <td class="text-center">
            <% if @defeated.include?(npc.id) %>
              <input type="checkbox" class="npc-toggle" data-path="<%= npc_remove_path(npc) %>" checked>
            <% else %>
              <input type="checkbox" class="npc-toggle" data-path="<%= npc_add_path(npc) %>">
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/npcs/show.html.erb
<% title(@npc.name) %>
<% description("Location: #{location(@npc, inline: true)} | " \
               "#{'Rule'.pluralize(@npc.rules.size)}: #{format_rules(@npc, inline: true)}") %>

<div class="row">
  <div class="col-12 col-sm-5 col-md-4 offset-0 offset-md-1 mb-3 mb-sm-0">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title"><%= format_npc_name(@npc) %></h5>
      </div>
      <div class="card-body">
        <dl>
          <dt>Location</dt>
          <dd><%= location(@npc, inline: true) %></dd>
          <dt>Patch</dt>
          <dd><%= @npc.patch %></dd>
          <% if @npc.rules.present? %>
            <dt><%= 'Rule'.pluralize(@npc.rules.size) %></dt>
            <dd><%= format_rules(@npc, inline: true) %></dd>
          <% end %>
          <dt>Difficulty</dt>
          <dd><%= difficulty(@npc) %></dd>
          <% if user_signed_in? %>
            <dt>Defeated</dt>
            <dd>
              <% if npc_defeated?(@npc) %>
                <%= fa_icon('check', text: 'Yes') %>
              <% else %>
                <%= fa_icon('times', text: 'No') %>
              <% end %>
            </dd>
          <% end %>
          <% if @npc.quest.present? %>
            <dt>Required Quest</dt>
            <dd><%= quest(@npc) %></dd>
          <% end %>
        </dl>
      </div>
    </div>
  </div>
  <div class="col-12 col-sm-7 col-md-6">
    <div class="card">
      <div class="card-header">
        <h5><%= 'Reward'.pluralize(@rewards.length) %></h5>
      </div>
      <div class="card-body">
        <div class="d-flex flex-wrap card-list-lg">
          <%= render partial: 'cards/large', collection: @rewards, as: :card %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row mt-4">
  <div class="col-12 col-md-10 offset-md-1">
    <div class="card">
      <div class="card-header d-flex justify-content-between align-items-center">
        <h5>Deck
          <span data-toggle="tooltip" data-html="true"
                                      title="Cards on the left are always used.<br>Cards on the right are chosen at random.">
            <%= fa_icon('question-circle') if @npc.variable_cards.present? %>
          </span>
        </h5>
        <div>
          <%= link_to 'Submit Deck', new_deck_path(npc_id: @npc.id), class: 'btn btn-primary btn-sm',
            data: { toggle: 'tooltip' }, title: 'Submit a deck to be used against this NPC' %>
          <%= link_to 'User Decks', decks_path(q: { npc_id_eq: @npc.id }),
            class: "btn btn-secondary btn-sm#{ ' disabled' unless Deck.exists?(npc_id: @npc.id) }",
            data: { toggle: 'tooltip' }, title: 'User decks designed to be used against this NPC' %>
        </div>
      </div>
      <div class="card-body pl-0">
        <div class="d-flex">
          <div class="d-flex <%= @npc.variable_cards.present? ? 'w-50' : 'w-100' %> flex-wrap
            align-self-start card-list-lg pl-3">
            <%= render partial: 'cards/large', collection: @npc.fixed_cards, as: :card, deck: true %>
          </div>
          <% if @npc.variable_cards.present? %>
            <div class="d-flex w-50 flex-wrap align-self-start card-list-lg variable-cards pl-3">
              <%= render partial: 'cards/large', collection: @npc.variable_cards, as: :card, deck: true %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>