config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', as: :new_user_session
    get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  post 'locale/set', to: 'locale#update'

  resources :cards, only: [:index, :show] do
    collection do
      get 'mine', to: redirect('cards')
      get 'select'
    end
  end

  get 'cards/no/:id', to: 'cards#no'
  get 'cards/ex/:id', to: 'cards#ex'

  get 'packs', to: 'card_packs#index'

  resources :npcs, only: [:index, :show] do
    post 'add'
    post 'remove'
    post 'defeated/update', on: :collection, to: 'npcs#update_defeated', as: :update_defeated
  end

  resources :cards, only: [] do
    post 'add'
    post 'remove'
    post 'set', on: :collection
  end

  resources :decks do
    get 'mine', as: :my, on: :collection
    post 'upvote'
    post 'downvote'
  end

  get 'users/:uid', to: 'users#show', as: :user
  get 'user/settings', to: 'users#edit'
  post 'user/settings', to: 'users#update'
  get 'user/import', to: 'users#import'
  post 'user/import', to: 'users#submit'

  namespace :api do
    %w(npcs cards packs decks).each do |model|
      resources model, only: [:index, :show], defaults: { format: :json }
    end

    resources :users, only: :show
  end

  get 'api/docs', to: redirect('https://documenter.getpostman.com/view/1779678/TzXzDHRR')

  get 'commands', to: 'static#commands'
  post 'discord/interactions'

  namespace :admin do
    resources :users, only: :index
    resources :npcs, only: [:index, :edit, :update]
    resources :cards, only: [:index, :edit, :update] do
      delete 'delete_sources'
    end
  end

  get '404', to: 'static#not_found', as: :not_found
  match "api/*path", via: :all, to: -> (_) { [404, { 'Content-Type' => 'application/json' },
                                              ['{"status": 404, "error": "Not found"}'] ] }
  match "*path", via: :all, to: redirect('404')

  # Quick 404 for missing images
  scope format: true, constraints: { format: 'png' } do
    get "/*missing", to: proc { [404, {}, ['']] }
  end

  root 'static#home'
end

app/models/deck.rb
# == Schema Information
#
# Table name: decks
#
#  id         :bigint(8)        not null, primary key
#  user_id    :integer
#  rule_id    :integer
#  npc_id     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  rating     :integer
#  notes      :string(1000)
#  updated    :boolean          default(TRUE)
#  user_uid   :string(255)
#

class Deck < ApplicationRecord
  before_create :set_order
  after_create :add_vote

  belongs_to :user, primary_key: :uid, foreign_key: :user_uid
  belongs_to :rule, required: false
  belongs_to :npc, required: false
  has_many :deck_cards, dependent: :delete_all
  has_many :cards, through: :deck_cards
  has_many :votes, dependent: :delete_all

  validates_with DeckValidator
  validates :rule, presence: true, unless: -> { rule_id.blank? }
  validates :npc,  presence: true, unless: -> { npc_id.blank? }

  def upvote(user)
    votes.find_or_create_by(user: user)
  end

  def downvote(user)
    votes.find_by(user: user)&.destroy
  end

  private
  def set_order
    deck_cards.each_with_index do |card, i|
      card.position = i + 1
    end
  end

  def add_vote
    votes.create!(user_id: user.id)
  end
end

app/controllers/api/decks_controller.rb
class Api::DecksController < ApiController
  def index
    @query_params = sanitize_query_params
    query = Deck.all.ransack(@query_params)
    @decks = query.result.includes(:user, :rule, :npc, cards: :type)
  end

  def show
    @deck = Deck.find_by(id: params[:id])
    render_not_found unless @deck.present?
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :set_user_cards, only: [:index, :mine, :show]
  before_action :signed_in?, except: [:index, :show]
  before_action :authenticated?, only: [:edit, :update, :destroy], unless: :admin?
  before_action :filter_query, only: [:index, :mine]

  def index
    @q = Deck.ransack(params[:q])
    @decks = @q.result.includes(:user, :rule, :npc, :cards).order(rating: :desc, id: :desc).paginate(page: params[:page])
  end

  def mine
    @q = current_user.decks.ransack(params[:q])
    @decks = @q.result.includes(:user, :rule, :npc, :cards).order(rating: :desc, id: :desc).paginate(page: params[:page])
    render :index
  end

  def show
    @user_card_ids = Card.where(id: @user_cards).order(:deck_order, :id).pluck(:id) if user_signed_in?
  end

  def new
    @deck = Deck.new(npc_id: params[:npc_id])
    set_search_and_cards
    set_new_edit_responses
  end

  def create
    @deck = current_user.decks.new(deck_params)

    if @deck.save
      redirect_to deck_path(@deck)
    else
      set_search_and_cards
      flash_errors(@deck)
      render :new
    end
  end

  def edit
    @deck = Deck.find(params[:id])
    set_search_and_cards
    set_new_edit_responses
    render :new
  end

  def update
    @deck.transaction do
      if @deck.card_ids != deck_params[:card_ids]
        @deck.deck_cards.delete_all
      end

      if @deck.update(deck_params)
        flash[:success] = 'The deck has been updated successfully.'
        redirect_to deck_path(@deck)
      else
        set_search_and_cards
        flash_errors(@deck)
        render :new
        raise ActiveRecord::Rollback
      end
    end
  end

  def destroy
    if @deck.destroy
      flash[:success] = 'The deck has been deleted successfully.'
    else
      flash[:error] = 'The deck could not be deleted.'
    end

    redirect_to decks_path
  end

  def upvote
    if @deck.upvote(current_user)
      flash[:success] = 'Your vote has been added.'
    else
      flash[:error] = 'There was a problem casting your vote.'
    end

    redirect_to deck_path(@deck)
  end

  def downvote
    if @deck.downvote(current_user)
      flash[:success] = 'Your vote has been removed.'
    else
      flash[:error] = 'There was a problem removing your vote.'
    end

    redirect_to deck_path(@deck)
  end

  private
  def set_deck
    @deck = Deck.find(params[:id] || params[:deck_id])
  end

  def set_user_cards
    @user_cards = current_user.cards.pluck(:id) if user_signed_in?
  end

  def authenticated?
    redirect_to decks_path unless @deck.user_id == current_user.id
  end

  def signed_in?
    unless user_signed_in?
      flash[:alert] = 'You must sign in to manage your decks.'
      redirect_to decks_path
    end
  end

  def admin?
    current_user&.admin?
  end


  def set_search_and_cards
    unless params[:source] == 'deck'
      @q = Card.ransack(params[:q])

      if params[:source] == 'search'
        @cards = @q.result.includes(:type).order(patch: :desc, order_group: :desc, order: :desc)
      else
        @cards = Card.includes(:type).order(patch: :desc, order_group: :desc, order: :desc).first(5)
      end
    end

    if ids = params[:card_ids]
      @deck.card_ids = ids.split(',')
    end
  end

  def set_new_edit_responses
    respond_to do |format|
      format.html
      format.js do
        case params[:source]
        when 'deck' then render 'deck_cards'
        when 'search' then render 'search_results'
        end
      end
    end
  end

  def filter_query
    params[:q] ||= {}

    if params[:general].present?
      params[:q].merge!(rule_id_null: true, npc_id_null: true)
    end

    if params[:updated].present?
      params[:q].merge!(updated_true: 1)
    end
  end

  def deck_params
    parms = params.require(:deck).permit(:card_ids, :rule_id, :npc_id, :notes)
    parms[:card_ids] = parms[:card_ids].split(',').map(&:to_i)
    parms
  end
end

app/helpers/decks_helper.rb
module DecksHelper
  def purpose(deck)
    if deck.npc_id.present?
      link_to(deck.npc.name, npc_path(deck.npc))
    elsif deck.rule_id.present?
      deck.rule.name
    else
      'General'
    end
  end

  def missing_cards(deck, user_cards)
    (deck.cards.pluck(:id) - user_cards).size
  end

  def usable?(deck, user_cards)
    missing = missing_cards(deck, user_cards)

    if missing == 0
      fa_icon('check', data: { toggle: 'tooltip', title: 'You have all of the cards in this deck.' })
    else
      fa_icon('times', data: { toggle: 'tooltip',
                               title: "You are missing #{missing} #{'card'.pluralize(missing)} from this deck." })
    end
  end

  def deck_patch(deck)
    if deck.updated?
      content_tag(:span, 'After 5.5', class: 'badge badge-primary')
    else
      content_tag(:span, 'Before 5.5', class: 'badge badge-secondary')
    end
  end

  def voted?(deck)
    Vote.exists?(deck: deck, user: current_user)
  end

  def card_position(card, user_card_ids)
    if index = user_card_ids.index(card.id)
      page = (index / 30) + 1
      row = (index % 30 / 5) + 1
      column = (index % 30 % 5) + 1

      "Page #{page}, Row #{row}, Column #{column}"
    else
      'This card is missing from your collection.'
    end
  end
end

app/views/decks/_builder_card.html.erb
<div class="d-flex flex-column deck-card" data-card-id="<%= card.id %>">
  <div class="card-large" data-toggle="tooltip" title="<%= card.name %>">
    <%= large_image(card) %>
  </div>
</div>

app/views/decks/_card.html.erb
<% if @user_cards.present? && !@user_cards.include?(card.id) %>
  <div class="card-missing">
    <%= yield %>
  </div>
<% else %>
  <%= yield %>
<% end %>

app/views/decks/deck_cards.js.erb
$('.card-list-lg').children().remove()
$('.card-list-lg').html("<%= j render partial: 'builder_card', collection: @deck.cards, as: :card %>")

app/views/decks/index.html.erb
<% title('Decks') %>

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header d-flex align-items-center justify-content-between">
        <% if user_signed_in? %>
          <h4 class="mb-0"><%= 'My ' if params[:action] == 'mine' %>Decks</h4>
          <div>
            <% if params[:action] == 'mine' %>
              <%= link_to 'All Decks', decks_path, class: 'btn btn-sm btn-primary' %>
            <% else %>
              <%= link_to 'My Decks', my_decks_path, class: 'btn btn-sm btn-primary' %>
            <% end %>
            <%= link_to 'New Deck', new_deck_path, class: 'btn btn-sm btn-success' %>
          </div>
        <% else %>
          <h4 class="mb-0">Decks</h4>
        <% end %>
      </div>
      <div class="card-body card-table">
        <%= search_form_for(@q, enforce_utf8: false, url: request.path, class: 'form form-inline search-form d-flex justify-content-center mx-2 my-3') do |f| %>
          <%= f.collection_select :rule_id_eq, Rule.all.sort_by(&:name), :id, :name, { include_blank: 'Filter by Rule' },
            class: 'form-control form-control-sm'%>
          <%= f.grouped_collection_select :npc_id_eq, Location.all.includes(:alphabetical_npcs), :alphabetical_npcs,
            :name, :id, :name, { include_blank: 'Filter by NPC' }, class: 'form-control form-control-sm'  %>
          <div class="form-check form-check-inline">
            <%= check_box_tag :general, 1, params[:general], class: 'form-check-input checkbox' %>
            <%= label_tag :general, 'General Use', class: 'form-check-label' %>
            <%= check_box_tag :updated, 1, params[:updated], class: 'form-check-input checkbox' %>
            <%= label_tag :updated, 'Only Updated', class: 'form-check-label' %>
          </div>
          <%= f.submit 'Search', name: nil, class: 'btn btn-secondary btn-sm' %>
        <% end %>
        <table class="table table-striped table-sm sortable">
          <thead>
            <tr>
              <th scope="col">Purpose</th>
              <th scope="col">Rating</th>
              <th scope="col">Created by</th>
              <th scope="col" class="text-center hide-xs" data-defaultsort="disabled">Cards</th>
              <% if user_signed_in? %>
                <th scope="col" class="text-center">Usable</th>
              <% end %>
              <th scope="col" class="text-center">Updated</th>
              <th data-defaultsort="disabled"></th> <!-- Buttons -->
            </tr>
          </thead>
          <tbody>
            <% @decks.each do |deck| %>
              <tr>
                <td><%= purpose(deck) %></td>
                <td><%= deck.rating %></td>
                <td><%= deck.user.username.truncate(20) %></td>
                <td class="hide-xs">
                  <div class="d-flex justify-content-center card-list">
                    <% deck.cards.each do |card| %>
                      <%= link_to(card_path(card), data: { toggle: 'tooltip', title: "#{card.name}" },
                                  class: ('card-missing' if @user_cards.present? && !@user_cards.include?(card.id))) do %>
                                  <%= small_image(card) %>
                                <% end %>
                              <% end %>
                  </div>
                </td>
                <% if user_signed_in? %>
                  <td class="text-center" data-value="<%= missing_cards(deck, @user_cards) == 0 %>">
                    <%= usable?(deck, @user_cards) %>
                  </td>
                <% end %>
                <td class="text-center"><%= deck_patch(deck) %></td>
                <td class="text-right">
                  <% if deck.user_id == current_user&.id %>
                    <%= link_to fa_icon('pencil', class: 'btn btn-secondary btn-sm'), edit_deck_path(deck) %>
                  <% end %>
                  <%= link_to fa_icon('list', class: 'btn btn-secondary btn-sm'), deck_path(deck) %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <% if will_paginate(@decks) %>
      <div class="card-footer d-flex justify-content-center">
        <%= will_paginate(@decks) %>
      </div>
    <% end %>
  </div>
</div>

app/views/decks/new.html.erb
<% title('Decks') %>

<%= form_for(@deck, html: { class: 'form deck-submit' }) do |f| %>
  <div class="row pb-3 d-flex align-items-stretch">
    <div class="col-12 col-sm-8 mb-3 mb-sm-0">
      <div class="card shadow h-100">
        <h5 class="card-header">Organize Deck</h5>
        <div class="card-body d-flex flex-column">
          <div class="d-flex card-list-lg flex-grow-1 flex-wrap" id="deck">
            <%= render partial: 'builder_card', collection: @deck.cards, as: :card %>
          </div>
          <div class="help<%= ' d-none' if @deck.cards.empty? %>">
            <hr>
            <p class="mt-3 ml-2">
              Click cards to remove them from your deck. Drag to reorder.
            </p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 col-sm-4">
      <div class="card shadow">
        <h5 class="card-header">Finalize Deck</h5>
        <div class="card-body">
          <%= f.hidden_field :card_ids, value: @deck.cards.map(&:id).join(',') %>
          <div class="form-group mb-2">
            <%= f.label :rule_id, 'Select a rule', class: 'mb-1' %>
            <%= f.collection_select :rule_id, Rule.all.sort_by(&:name), :id, :name, { include_blank: true },
              class: 'form-control form-control-sm' %>
          </div>
          <div class="form-group mb-2">
            <%= f.label :npc_id, 'or an NPC', class: 'mb-1' %>
            <%= f.grouped_collection_select :npc_id, Location.all.includes(:alphabetical_npcs), :alphabetical_npcs,
              :name, :id, :name, { include_blank: true }, class: 'form-control form-control-sm'  %>
          </div>
          <span>or just create a general purpose deck.</span>
          <hr class="my-3">
          <div class="text-right mb-2">
            <%= f.submit 'Publish Deck', class: 'btn btn-primary btn-sm', disabled: @deck.cards.size != 5 %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row pb-3">
    <div class="col-12">
      <div class="card shadow">
        <h5 class="card-header">Notes</h5>
        <div class="card-body">
          <div class="form-group">
            <%= f.text_area :notes, { rows: 3, maxlength: 1000, class: 'form-control' } %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
<div class="row">
  <div class="col-12">
    <div class="card shadow">
      <h5 class="card-header">Find Cards</h5>
      <div class="card-body card-table">
        <%= search_form_for(@q, class: 'form form-inline search-form d-flex justify-content-center mx-2 my-3', url: new_deck_path, enforce_utf8: false) do |f| %>
          <%= f.search_field "name_#{I18n.locale}_cont", placeholder: 'Name', size: 30, class: 'form-control form-control-sm' %>
          <%= f.search_field 'order_eq', placeholder: 'Number', size: 10, class: 'form-control form-control-sm' %>
          <%= f.collection_select :card_type_id_eq, CardType.all, :id, :name,
            { include_blank: 'All Types' }, class: 'form-control form-control-sm' %>
          <%= f.select :stars_eq, rarity_options, { include_blank: 'All Rarities' }, class: 'form-control form-control-sm' %>
          <%= submit_tag 'Search', name: nil, class: 'btn btn-secondary btn-sm' %>
        <% end %>
        <table class="table table-striped table-sm search-results sortable">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col"></th> <!-- Image -->
              <th scope="col" class="hide-xs">Name</th>
              <th scope="col">Type</th>
              <th scope="col">Rarity</th>
              <th scope="col" class="text-center">Stats</th>
              <th scope="col" data-defaultsort="disabled"></th> <!-- Add to deck -->
            </tr>
          </thead>
          <tbody>
            <%= render 'cards/table_data', cards: @cards, skip_source: true, deck: @deck.cards.map(&:id) %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/decks/search_results.js.erb
$('tbody tr').remove()
$('tbody').html("<%= j render 'cards/table_data', cards: @cards, skip_source: true, deck: @deck.cards.map(&:id) %>")

app/views/decks/show.html.erb
<% title('Decks') %>
<% description("#{purpose(@deck)} deck by #{@deck.user.username}") %>

<div class="row">
  <div class="col-12 col-md-4 mb-3 mb-md-0">
    <div class="card">
      <div class="card-header d-flex justify-content-between align-items-center py-2">
        <h5 class="card-title">Details</h5>
        <div>
          <% if current_user&.id == @deck.user_id %>
            <%= link_to 'Edit', edit_deck_path(@deck), class: 'btn btn-secondary btn-sm' %>
          <% end %>
          <% if current_user&.id == @deck.user_id || current_user&.admin? %>
            <%= link_to 'Delete', deck_path(@deck), method: :delete, class: 'btn btn-danger btn-sm',
              data: { confirm: 'Are you sure you want to delete this deck?' } %>
          <% end %>
        </div>
      </div>
      <div class="card-body">
        <dl>
          <dt>Purpose</dt>
          <dd><%= purpose(@deck) %></dd>
          <dt>Rating</dt>
          <dd><%= @deck.rating %></dd>
          <% if user_signed_in? %>
            <dt>Usable</dt>
            <dd><%= usable?(@deck, @user_cards) %></dd>
          <% end %>
          <dt>Updated</dt>
          <dd>
            <%= deck_patch(@deck) %>
          </dd>
          <dt>Created by</dt>
          <dd><%= @deck.user.username %></dd>
        </dl>
      </div>
    </div>
  </div>
  <div class="col-12 col-md-8">
    <div class="card">
      <div class="card-header d-flex justify-content-between align-items-center py-2">
        <h5>Cards</h5>
        <% if user_signed_in? %>
          <% if voted?(@deck) %>
            <%= link_to fa_icon('check-circle', text: 'Voted'), deck_downvote_path(@deck), method: :post,
              class: 'btn btn-success btn-sm vote-down' %>
          <% else %>
            <%= link_to fa_icon('arrow-circle-up', text: 'Vote'), deck_upvote_path(@deck), method: :post,
              class: 'btn btn-primary btn-sm vote-up' %>
          <% end %>
        <% end %>
      </div>
      <div class="card-body">
        <div class="d-flex flex-wrap card-list-lg">
          <%= render partial: 'cards/large', layout: 'card', collection: @deck.cards, as: :card %>
        </div>
      </div>
    </div>
    <% if @deck.notes.present? %>
      <div class="card mt-3">
        <h5 class="card-header">Notes</h5>
        <div class="card-body py-3">
          <%= @deck.notes.gsub("\r\n", '<br>').html_safe %>
        </div>
      </div>
    <% end %>
    <% if user_signed_in? %>
      <div class="card mt-3">
        <h5 class="card-header">Card Finder</h5>
        <div class="card-body">
          <% @deck.cards.each_with_index do |card, i| %>
            <p>
              <b><%= link_to(card.name, card_path(card), class: 'unstyled') %>:</b>
              <%= card_position(card, @user_card_ids) %>
            </p>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>