config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', as: :new_user_session
    get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  post 'locale/set', to: 'locale#update'

  resources :cards, only: [:index, :show] do
    collection do
      get 'mine', to: redirect('cards')
      get 'select'
    end
  end

  get 'cards/no/:id', to: 'cards#no'
  get 'cards/ex/:id', to: 'cards#ex'

  get 'packs', to: 'card_packs#index'

  resources :npcs, only: [:index, :show] do
    post 'add'
    post 'remove'
    post 'defeated/update', on: :collection, to: 'npcs#update_defeated', as: :update_defeated
  end

  resources :cards, only: [] do
    post 'add'
    post 'remove'
    post 'set', on: :collection
  end

  resources :decks do
    get 'mine', as: :my, on: :collection
    post 'upvote'
    post 'downvote'
  end

  get 'users/:uid', to: 'users#show', as: :user
  get 'user/settings', to: 'users#edit'
  post 'user/settings', to: 'users#update'
  get 'user/import', to: 'users#import'
  post 'user/import', to: 'users#submit'

  namespace :api do
    %w(npcs cards packs decks).each do |model|
      resources model, only: [:index, :show], defaults: { format: :json }
    end

    resources :users, only: :show
  end

  get 'api/docs', to: redirect('https://documenter.getpostman.com/view/1779678/TzXzDHRR')

  get 'commands', to: 'static#commands'
  post 'discord/interactions'

  namespace :admin do
    resources :users, only: :index
    resources :npcs, only: [:index, :edit, :update]
    resources :cards, only: [:index, :edit, :update] do
      delete 'delete_sources'
    end
  end

  get '404', to: 'static#not_found', as: :not_found
  match "api/*path", via: :all, to: -> (_) { [404, { 'Content-Type' => 'application/json' },
                                              ['{"status": 404, "error": "Not found"}'] ] }
  match "*path", via: :all, to: redirect('404')

  # Quick 404 for missing images
  scope format: true, constraints: { format: 'png' } do
    get "/*missing", to: proc { [404, {}, ['']] }
  end

  root 'static#home'
end

app/views/layouts/_alerts.html.erb
<% flash.to_hash.except('timedout').each do |key, value| %>
  <div class="alert alert-dismissable fade show <%= flash_class(key) %>">
    <% unless key =~ /fixed/ %>
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        <%= fa_icon 'times' %>
      </button>
    <% end %>
    <%= value.html_safe %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-md navbar-dark mb-2">
  <%= link_to root_path, class: 'navbar-brand' do %>
    <%= image_tag('logo.png') %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent"
          aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarContent">
    <div class="navbar-nav mr-auto">
      <%= nav_link('Cards', cards_path, 'cards') %>
      <%= nav_link('NPCs', npcs_path, 'npcs') %>
      <%= nav_link('Decks', decks_path, 'decks') %>
      <%= nav_link('Packs', packs_path) %>
      <%= nav_link('Discord Commands', commands_path) %>
      <div class="navbar-nav nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="otherDropdown" role="button" data-toggle="dropdown"
           aria-haspopup="true" aria-expanded="false">Other</a>
        <div class="dropdown-menu" aria-labelledBy="otherDropdown">
          <%= play_guide_link %>
          <%= play_online_link %>
          <%= ffxiv_collect_link %>
        </div>
      </div>
    </div>
    <div class="navbar-nav nav-item dropdown">
      <a class="nav-link dropdown-toggle p-0 pr-3" href="#" id="localeDropdown" role="button" data-toggle="dropdown"
        aria-haspopup="true" aria-expanded="false"><%= cookies[:locale].upcase %></a>
      <div class="dropdown-menu" aria-labelledBy="localeDropdown">
        <% %w(EN DE FR JA).each do |locale| %>
          <%= link_to locale, locale_set_path(locale: locale), class: 'dropdown-item', method: :post %>
        <% end %>
      </div>
    </div>
    <% if user_signed_in? %>
      <div class="navbar-nav nav-item mr-2">
        <%= avatar(current_user) %>
      </div>
      <div class="navbar-nav nav-item dropdown">
        <a class="nav-link dropdown-toggle p-0" href="#" id="userDropdown" role="button" data-toggle="dropdown"
           aria-haspopup="true" aria-expanded="false"><%= current_user.username %></a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
          <% if current_user.admin? %>
            <%= link_to fa_icon('user', text: 'Manage Users'), admin_users_path, class: 'dropdown-item' %>
            <%= link_to fa_icon('file', text: 'Manage Cards'), admin_cards_path, class: 'dropdown-item' %>
            <%= link_to fa_icon('address-book', text: 'Manage NPCs'), admin_npcs_path, class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
          <% end %>
          <%= link_to fa_icon('user', text: 'Profile'), user_path(current_user.uid), class: 'dropdown-item' %>
          <%= link_to fa_icon('wrench', text: 'Settings'), user_settings_path, class: 'dropdown-item' %>
          <%= link_to fa_icon('sign-out', text: 'Sign Out'), destroy_user_session_path, class: 'dropdown-item' %>
        </div>
      </div>
    <% else %>
      <%= link_to 'Sign in with Discord', user_discord_omniauth_authorize_path, method: :post, class: 'btn btn-secondary' %>
    <% end %>
  </div>
</div>

app/views/layouts/_progress.html.erb
<div class="progress">
  <div class="progress-bar" role="progressbar" style="width: <%= (value / max.to_f) * 100 %>%;"
    aria-valuenow="<%= value %>" aria-valuemin="0" aria-valuemax="<%= max %>">
    <% if max > 0 %>
      <b class="px-2"><%= value %>/<%= max %> (<%= ((value / max.to_f) * 100).to_i %>%)</b>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#CAA665">
    <link rel="icon" type="image/x-icon" href="/favicon.ico">

    <title><%= yield_title('Another Triple Triad Tracker') %></title>
    <meta name="description"
      content="<%= yield_description('Another website for tracking your Final Fantasy XIV Triple Triad card collection.') %>">
    <meta property="og:title" content="<%= yield_title('Another Triple Triad Tracker') %>">
    <meta property="og:description"
      content="<%= yield_description('Another website for tracking your Final Fantasy XIV Triple Triad card collection.') %>">
    <meta property="og:image" content="<%= yield_image(image_path('logo.png', skip_pipeline: true)) %>">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="container mb-4">
      <%= render 'layouts/navbar' %>
      <%= render 'layouts/alerts' %>
    </header>

    <main role="main" class="container<%= ' ja' if I18n.locale == :ja %>">
      <%= yield %>
    </main>

    <footer class="text-center">
      <span class='d-block d-sm-inline'>Created by Raelys Skyborn of Behemoth</span>
      <span class="d-none d-sm-inline"> | </span>
      <div class="d-block d-sm-inline">
        <span>Powered by <%= link_to 'Saint Coinach', 'https://github.com/ufx/SaintCoinach', target: '_blank' %> | </span>
        <%= link_to 'https://discord.gg/QVypqNn2cg', class: 'unstyled', target: '_blank' do %>
          <%= image_tag('discord.png', class: 'discord') %>
        <% end %>
        <%= link_to 'https://github.com/mattantonelli/ffxiv-triple-triad', class: 'unstyled', target: '_blank' do %>
          <%= image_tag('github.png', class: 'github') %>
        <% end %>
        <%= link_to 'https://www.patreon.com/raelys', class: 'unstyled', target: '_blank' do %>
          <%= image_tag('patreon.png', class: 'patreon') %>
        <% end %>
      </div>
    </footer>
  </body>
</html>